name: private_pub
description: A private Pub server implementation built with the Angel framework.
author: Tobe O <thosakwe@gmail.com>
environment:
  sdk: ">=2.0.0 <3.0.0"
dependencies:
  angel_configuration: ^2.0.0
  angel_framework: ^2.0.0-alpha
  angel_jael: ^2.0.0
  angel_migration: ^2.0.0-alpha
  angel_migration_runner: ^2.0.0-alpha
  angel_model: ^1.0.0
  angel_orm: ^2.0.0-dev
  angel_orm_postgres: ^1.0.0-dev
  angel_production: ^1.0.0-alpha
  angel_serialize: ^2.0.0
  angel_static: ^2.0.0
  angel_validate: ^2.0.0
  archive: ^2.0.0
  args: ^1.0.0
  dbcrypt: ^1.0.0
  path: ^1.0.0
  prompts: ^1.0.0
  pubspec_parse: ^0.1.3
dev_dependencies:
  angel_hot: ^2.0.0
  angel_orm_generator: ^2.0.0-dev
  angel_serialize_generator: ^2.0.0
  build_runner: ^1.0.0
executables:
  ppub: ppub
